#!/usr/bin/env ruby

require 'fileutils'
require 'getoptlong'
require 'yaml'

include FileUtils

conf = YAML.load_file("#{ENV['HOME']}/.akerrc")
$id_file = conf['id_file']
$user = conf['user']
$tmp_dir = conf['tmp_dir']
$editor = conf['editor'] || ENV['EDITOR']
$gpg_cmd = conf['gpg_cmd'] || 'gpg'

def list
  yaml = IO.popen("#{$gpg_cmd} -q -d #{$id_file}")
  id_entries = YAML.load(yaml)
  puts id_entries.keys.sort.join("\n")
end

def search(search_str)
  yaml = IO.popen("#{$gpg_cmd} -q -d #{$id_file}")
  id_entries = YAML.load(yaml)
  first = true

  id_entries.each do |name, attrs|
    if name.match(/#{search_str}/) || attrs.to_s.match(/#{search_str}/)
      puts unless first
      first = false

      puts name
      puts attrs.to_yaml
    end
  end
end

def edit
  id_file_bn = File.basename($id_file)
  id_file_bn_noext = File.basename($id_file, ".gpg")

  cp($id_file, "#{$id_file}.bak")
  tmp_file = `mktemp -p #{$tmp_dir} #{id_file_bn_noext}.tmp.XXXXXXXXXX`
  tmp_file.chomp!
  system("#{$gpg_cmd} -q -d #{$id_file} > #{tmp_file}")
  cp(tmp_file, "#{tmp_file}.orig")
  system("#{$editor} #{tmp_file}")
  unless system("diff #{tmp_file} #{tmp_file}.orig > /dev/null")
    if system("#{$gpg_cmd} -e -r #{$user} #{tmp_file}")
      mv("#{tmp_file}.gpg", $id_file)
    end
  end
  rm([tmp_file, "#{tmp_file}.orig"], :force => true)
end

opts = GetoptLong.new(
  [ '--list',   '-l', GetoptLong::NO_ARGUMENT ],
  [ '--edit',   '-e', GetoptLong::NO_ARGUMENT ],
  [ '--search', '-s', GetoptLong::REQUIRED_ARGUMENT ]
)

begin
  opts.each do |opt, arg|
    case opt
    when '--edit'
      edit
    when '--list'
      list
    when '--search'
      search(arg)
    end
  end
rescue GetoptLong::Error => e
  exit 1
end
